[package]
name = "simple-log"
version = "0.1.0"
authors = ["Alex <flowalex@vivaldi.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.nickel]

git = "https://github.com/nickel-org/nickel.rs.git"
